exclude: "secrets/.*"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        exclude_types: [markdown]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/nix-community/nixpkgs-fmt/
    rev: f4c3f141c2821589198bffe07f2f45681540504f
    hooks:
      - id: nixpkgs-fmt
