{
  programs.kitty = {
    enable = true;
    settings = {
      scrollback_lines = 100000;
      enable_audio_bell = false;
      update_check_interval = 0;
      allow_hyperlinks = true;
    };
    extraConfig = ''
      include dank-theme.conf

      # dank-theme.conf is regenerated by DankMaterialShell's matugen
      # integration from the current wallpaper, and several of its ANSI
      # slots don't have reliable contrast against the background in both
      # light and dark mode (yellow/cyan in light mode, magenta in both -
      # e.g. fast-syntax-highlighting's path color). Pin those slots to
      # fixed, contrast-checked colors so the zsh prompt (directory
      # highlight, git-dirty status), fast-syntax-highlighting (path
      # highlighting), and any other tool relying on these ANSI colors
      # stay readable in both modes, regardless of theme regeneration.
      color3   #9a6a00
      color11  #c9900f
      color5   #e50091
      color13  #f433f4
      color6   #2f6bd6
      color14  #5b8dff
    '';
  };
}
