name: Deploy Latest Generation

on:
  push:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        override: true
    - name: Install pre-commit
      run: |
        pip install pre-commit
        pre-commit install --install-hooks
    - name: Run pre-commit
      run: |
        pre-commit run -av

  switch_commit:
    name: Switch Commit
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        host:
          - kessel.nevarro.space
          - morak.sumnerevans.com

    steps:
      - uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Switch commit on ${{ matrix.host }}
        run: |
          ssh root@${{ matrix.host }}  "cd /etc/nixos && git fetch && git reset --hard $(git rev-parse HEAD)"

  remote_build:
    name: Remote Build
    runs-on: ubuntu-latest
    needs: [ switch_commit ]
    strategy:
      fail-fast: false
      matrix:
        host:
          - kessel.nevarro.space
          - morak.sumnerevans.com

    steps:
      - uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Remote build on ${{ matrix.host }}
        run: |
          ssh root@${{ matrix.host }}  "time nixos-rebuild build --show-trace"

  switch_generation:
    name: Switch Generation
    runs-on: ubuntu-latest
    needs: [ remote_build, lint ]
    strategy:
      fail-fast: false
      matrix:
        host:
          - kessel.nevarro.space
          - morak.sumnerevans.com

    steps:
      - uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Switch generation on ${{ matrix.host }}
        run: |
          ssh root@${{ matrix.host }}  "time nixos-rebuild switch --show-trace"
