name: Lint

on:
  push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        override: true
    - name: Install pre-commit
      run: |
        pip install pre-commit
        pre-commit install --install-hooks
    - name: Run pre-commit
      run: |
        pre-commit run -av
